[book]
title = "uvup Documentation"
authors = ["KercyDing"]
language = "en"
multilingual = false
src = "book/src"
description = "A conda-like environment manager for uv"

[build]
build-dir = "book/build"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/KercyDing/uvup"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/KercyDing/uvup/edit/main/{path}"

[output.html.fold]
enable = false

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true

[output.html.print]
enable = true
