[book]
title = "uvup 文档"
authors = ["KercyDing"]
language = "zh"
src = "book/src/zh"
description = "类似 conda 的 uv 环境管理器"

[build]
build-dir = "book/build/zh"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/KercyDing/uvup"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/KercyDing/uvup/edit/main/{path}"
additional-js = ["lang-zh.js"]

[output.html.fold]
enable = false

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true

[output.html.print]
enable = true
